version: "3.9"

services:
  sqlite3:
    image: nouchka/sqlite3:latest

  node:
    image: node:18.16.1
    depends_on:
      - sqlite3
    environment:
      - NODE_ENV=production
    volumes:
      - nodemodules:/usr/src/essay/node_modules
      # 当前目录对应的docker中容器的目录
      - ./:/usr/src/essay
    working_dir: /usr/src/essay
    command: /bin/sh -c "npm config set registry https://registry.npm.taobao.org && npm install -g --force yarn && yarn install --production && npm start"
    ports:
      - "7001:7001"

volumes:
  nodemodules:
